server:
  port: 8099
  #24 * 60 * 60 * 1000
  oneDay: 86400000
  #0 * 1000
  initDelay: 0
  jsonPath: E:/datax_json
  dataxPath: E:/Project/DataX-import/target/datax-v1.0.3-hashdata/datax/bin/datax.py

